[package]
name = "serde_ignored"
version = "0.0.1" # update version in readme for breaking changes
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Find out about keys that are ignored when deserializing data"
repository = "https://github.com/dtolnay/serde-ignored"
keywords = ["serde"]
categories = ["encoding"]

[dependencies]
serde = "0.9"

[dev-dependencies]
serde_derive = "0.9"
serde_json = "0.9"
